#!/bin/bash

PUSH_FLAG=false

if [ "$1" = "-p" ]; then
   PUSH_FLAG=true
fi

CMD="./mvnw clean package -DskipTests -Dquarkus.container-image.build=true -Dquarkus.jib.platforms=linux/amd64,linux/aarch64 -Dquarkus.container-image.push=$PUSH_FLAG -Dquarkus.container-image.labels.org.opencontainers.image.source=https://github.com/vino9org/fund-transfer-k8s "
echo $CMD
$CMD
