quarkus:
  application:
    name: fund-transfer
  container-image:
    registry: ghcr.io
    group: vino9org
    name: fund-transfer
  rest-client:
    core-banking-api:
      url: http://core-banking-sim:8000
      scope: javax.inject.Singleton
  log:
    level: INFO
    console:
      json: false
  jib:
    jvm-arguments: "-javaagent:/newrelic/newrelic.jar"

"%dev":
  quarkus:
    log:
      console:
        json: false

"%test":
  quarkus:
    log:
      console:
        json: false
    rest-client:
      core-banking-api:
        url: http://localhost:8000
        scope: javax.inject.Singleton
