quarkus:
  application:
    name: fund-transfer
  container-image:
    registry: docker.io
    group: sloppycoder
    name: vinobank-fund-transfer
  rest-client:
    core-banking-api:
      url: http://corebanking-sim:8000
      scope: javax.inject.Singleton
  opentelemetry:
    enabled: true
    propagators: tracecontext,baggage,ottrace,xray
    tracer:
      exporter:
        otlp:
          endpoint: http://${OLTP_COLLECTOR_IP:127.0.0.1}:4317
  log:
    level: INFO

api:
  limits-api:
    base-url: https://6a197tkp25.execute-api.us-west-2.amazonaws.com/prod
    aws-region: us-west-2


"%dev":
  quarkus:
    log:
      console:
        json: false

"%test":
  quarkus:
    log:
      console:
        json: false
    rest-client:
      core-banking-api:
        url: http://localhost:8000
        scope: javax.inject.Singleton
