quarkus:
  application:
    name: fund-transfer
  container-image:
    registry: ghcr.io
    group: vino9org
    name: fund-transfer
  stork:
    core-banking-sim:
      service-discovery:
        type: kubernetes
        k8s-namespace: vinobank
        port-name: http
      load-balancer:
        type: round-robin

  log:
    level: INFO
    console:
      json: false
  jib:
    jvm-arguments: "-javaagent:/newrelic/newrelic.jar"

"%dev":
  quarkus:
    http:
      port: 8888
    log:
      console:
        json: false

"%test":
  quarkus:
    log:
      console:
        json: false
    rest-client:
      core-banking-api:
        url: http://localhost:8000
        scope: javax.inject.Singleton
