kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base
  - ingress.yaml

namespace: vinobank

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: newrelic-license
    envs:
      - newrelic_lic.env